spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shortener
    username: shortener
    password: shortener
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info
